[package]
name = "bench-soft-ratatui"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bevy.workspace = true
ratatui.workspace = true
renderer-bench-sdk.workspace = true
soft_ratatui = { version = "0.2.0", default-features = false, features = ["embedded-ttf"] }

[lints.clippy]
all = "warn"
