[package]
name = "bench-empty-bevy"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
bevy.workspace = true
ratatui.workspace = true
renderer-bench-sdk.workspace = true

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "warn"
