#!/usr/bin/env python3
"""Generate bevy_terminal's Nerd Font constraint table from Ghostty.

Usage: gen_nerd_font_table.py <ghostty checkout> > \
    crates/bevy_terminal/src/render/batch/nerd_font.rs

Reads Ghostty's generated `src/font/nerd_font_attributes.zig` (derived from
the Nerd Fonts patcher by `nerd_font_codegen.py`) and writes the same data as
a compact Rust table: deduplicated constraints plus sorted codepoint ranges.
Ghostty is MIT licensed (Copyright (c) 2024 Mitchell Hashimoto, Ghostty
contributors).
"""
import re
import subprocess
import sys

root = sys.argv[1]
source = open(f"{root}/src/font/nerd_font_attributes.zig").read()
revision = subprocess.run(
    ["git", "-C", root, "rev-parse", "HEAD"], capture_output=True, text=True, check=True
).stdout.strip()

body = source[source.index("return switch (cp) {") :]
entries = re.findall(r"((?:\s*0x[0-9a-f]+(?:\.\.\.0x[0-9a-f]+)?,)+)\s*=>\s*\.\{(.*?)\n        \}", body, re.S)

ENUMS = {
    "size": ("Size", {"none": "None", "fit": "Fit", "cover": "Cover", "fit_cover1": "FitCover1", "stretch": "Stretch"}),
    "align_horizontal": ("Align", {"none": "None", "start": "Start", "end": "End", "center": "Center", "center1": "Center1"}),
    "align_vertical": ("Align", {"none": "None", "start": "Start", "end": "End", "center": "Center", "center1": "Center1"}),
    "height": ("Height", {"cell": "Cell", "icon": "Icon"}),
}
FLOATS = ["pad_top", "pad_left", "pad_right", "pad_bottom", "relative_width", "relative_height", "relative_x", "relative_y"]


def rust_float(text):
    value = float(text)
    literal = repr(value)
    return literal if "." in literal or "e" in literal else literal + ".0"


constraints = []
ranges = []
for codepoints, attributes in entries:
    fields = dict(re.findall(r"\.(\w+)\s*=\s*([^,\n]+),", attributes))
    parts = []
    for name, value in fields.items():
        if name in ENUMS:
            type_name, variants = ENUMS[name]
            parts.append(f"{name}: {type_name}::{variants[value.lstrip('.')]}")
        elif name in FLOATS:
            parts.append(f"{name}: {rust_float(value)}")
        elif name == "max_xy_ratio":
            parts.append(f"max_xy_ratio: Some({rust_float(value)})")
        elif name == "max_constraint_width":
            parts.append(f"max_constraint_width: {int(value)}")
        else:
            raise SystemExit(f"unknown constraint field {name}")
    constraint = ", ".join(parts)
    if constraint not in constraints:
        constraints.append(constraint)
    index = constraints.index(constraint)
    for item in re.findall(r"0x[0-9a-f]+(?:\.\.\.0x[0-9a-f]+)?", codepoints):
        start, _, end = item.partition("...")
        ranges.append((int(start, 16), int(end or start, 16), index))

ranges.sort()
for (_, previous_end, _), (start, _, _) in zip(ranges, ranges[1:]):
    assert previous_end < start, "overlapping ranges"
merged = []
for start, end, index in ranges:
    if merged and merged[-1][2] == index and merged[-1][1] + 1 == start:
        merged[-1] = (merged[-1][0], end, index)
    else:
        merged.append((start, end, index))

print(f"""//! Nerd Font glyph constraints.
//!
//! Generated by `ghostty-parity/gen_nerd_font_table.py` from Ghostty's
//! `src/font/nerd_font_attributes.zig` (which Ghostty derives from the Nerd
//! Fonts patcher) at `{revision}`.
//! Do not edit by hand.
//!
//! Ghostty is MIT licensed: Copyright (c) 2024 Mitchell Hashimoto, Ghostty
//! contributors.

use super::constraint::{{Align, Constraint, Height, Size}};

/// The distinct constraints [`RANGES`] refers to.
pub(super) static CONSTRAINTS: [Constraint; {len(constraints)}] = [""")
for constraint in constraints:
    print(f"    Constraint {{ {constraint}, ..Constraint::NONE }},")
print(f"""];

/// Sorted, disjoint inclusive codepoint ranges and their constraint.
pub(super) static RANGES: [(u32, u32, u16); {len(merged)}] = [""")
for start, end, index in merged:
    print(f"    (0x{start:04x}, 0x{end:04x}, {index}),")
print("""];""")
